
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
import javax.swing.JPanel;
import java.io.File;
import java.io.IOException;
import java.util.*;
import java.io.FileNotFoundException;
/**
 *
 * @author dales
 */
public class SearchBarFrame extends javax.swing.JFrame{

    /**
     * Creates new form TestFrame
     */
        public String test = "hello world";
    public SearchBarFrame(Main main) {
        initComponents();
        
        
        
//        JPanel panel = new SearchBar();
//        this.add(panel);
//        panel.setVisible(true);





    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        searchButton = new javax.swing.JButton();
        textInput = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        searchButton.setText("Search");
        searchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(textInput, javax.swing.GroupLayout.DEFAULT_SIZE, 337, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(searchButton, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(searchButton)
                    .addComponent(textInput, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 277, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    // when the search button is pressed, it will take the text enterend in the text field and compare it to the database to find recipes
    private void searchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchButtonActionPerformed
        // TODO add your handling code here:
//        if (test.equals(textInput.getText())){
//            System.out.println("they are equal");
//        }
//        else{
//            System.out.println("They are not equal");
//        }
try{
File file = new File("WitcheverFileName.txt"); //initialize File object and passing path as argument.
Scanner recipes = new Scanner(file); // able to scan through file

String line = ""; // stores each line in the file
List<String> result = new LinkedList<>(); // stores all results that include the words in the search
while(recipes.hasNextLine()){
    line = recipes.nextLine();
    if (line.contains(textInput.getText())){
        result.add(line);
    }
}

for (String each : result){
    System.out.println(each);
}

recipes.close();

}catch(Exception e){
        System.out.println("File not found!");
    }

    }//GEN-LAST:event_searchButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton searchButton;
    private javax.swing.JTextField textInput;
    // End of variables declaration//GEN-END:variables
}
